services:
  server:
    image: zackjh/roundabarter-server:x64
    container_name: roundabarter-server
    volumes:
      - roundabarter-db:/etc/roundabarter
    environment:
      DATABASE_LOCATION: /etc/roundabarter/database.db
  telegram-bot:
    image: zackjh/roundabarter-telegram-bot:x64
    container_name: roundabarter-telegram-bot
    environment:
      TELEGRAM_BOT_API_TOKEN: <YOUR TELEGRAM BOT TOKEN>
      FLASK_API_URL: http://roundabarter-server:5000
      DEFAULT_SCRAPE_INTERVAL: 600
      LIST_OF_ADMINS: "[<YOUR TELEGRAM USER ID>]"

volumes:
  roundabarter-db:
